services:
  - type: web
    name: wasabi-bot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    disk:
      name: session
      mountPath: /app/session
      sizeGB: 1
